spring:
  datasource:
    url: jdbc:postgresql://dpg-d1d2niidbo4c73cb08p0-a.singapore-postgres.render.com:5432/financetracker_q2k7
    username: financeuser
    password: E1imNmA8AVpTd3Y5ti7dfZpTnk1PvQLp
    driver-class-name: org.postgresql.Driver

  main:
    web-application-type: servlet

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  jwtSecret: ${APP_JWT_SECRET:qUChgJtRn774puTo+wi3dFYWh72ypl4rILdga9280BM=}
  jwtExpirationMs: ${APP_JWT_EXPIRATION_MS:86400000} # 24 hours
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,https://finance-tracker-react-five.vercel.app}

  jackson:
    serialization:
      indent_output: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.springframework.boot.autoconfigure: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Enable full condition evaluation logging
debug: true

---
# Enable actuator endpoints (optional)
management:
  endpoints:
    web:
      exposure:
        include: "*"
